#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when apcupsd
# detects that the battery should be replaced.
#

/etc/apcupsd/send_telegram_message.sh "Battery needs changing NOW"

exit 0
