#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when the    
# UPS goes back on to the mains after a power failure.
#

/etc/apcupsd/send_telegram_message.sh "Power has returned"

exit 0
